### ISSUE TITLE
Please publish a LICENSE

### ISSUE THREAD

**Issue by mjuszczak** [mindbody/API-Examples#16]
We want to release code we built using these code samples open source, but we can't without there being a LICENSE file on these code samples indicating what the license is -- apache 2.0, etc. Please advise and update if you can? Thanks!

**Comment by vacoj** [comment]
Thank you for pointing this out.  I'll see what I can do about getting this updated ASAP.

**Comment by mjuszczak** [comment]
Thanks!

**Comment by Guinto** [comment]
This has now been resolved with the latest commit. Thank you for bringing this to our attention.
